# Generated by Django 3.1 on 2020-08-11 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car2',
            name='eng2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rel.engine2'),
        ),
    ]
