# Generated by Django 3.1 on 2020-08-11 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rel', '0002_auto_20200811_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=75)),
                ('state', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rel.birthplace')),
            ],
        ),
        migrations.RemoveField(
            model_name='car2',
            name='eng2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cu',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Car2',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Engine',
        ),
        migrations.DeleteModel(
            name='Engine2',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
