# Generated by Django 3.1 on 2020-08-11 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rel', '0003_auto_20200811_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='birthplace',
            new_name='bp',
        ),
    ]
